# .github/workflows/extract-frames.yml
# ======================================
# Daily pipeline: extract heatmap frames from YouTube videos,
# generate image variants, upload to R2, catalog in Neon.
#
# Required secrets:
#   DATABASE_URL       — Neon PostgreSQL connection string
#   R2_ENDPOINT        — Cloudflare R2 endpoint
#   R2_ACCESS_KEY_ID   — R2 access key
#   R2_SECRET_ACCESS_KEY — R2 secret key
#
# Optional:
#   SLACK_WEBHOOK_URL  — Slack webhook for failure notifications

name: Daily Content Pipeline

on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC daily

  workflow_dispatch:
    inputs:
      video_urls:
        description: "Comma-separated YouTube URLs (optional override)"
        required: false
        type: string

env:
  PYTHON_VERSION: "3.12"
  R2_BUCKET: "framedle-content"

jobs:
  extract-frames:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: pipeline/requirements.txt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ffmpeg

      - name: Install Python dependencies
        run: pip install -r pipeline/requirements.txt

      - name: Run frame extraction
        working-directory: pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ env.R2_BUCKET }}
        run: |
          if [ -n "${{ github.event.inputs.video_urls }}" ]; then
            python extract_batch.py --urls "${{ github.event.inputs.video_urls }}"
          else
            python extract_batch.py
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Pipeline failed! Check logs above."
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"⚠️ Framedle pipeline failed! Check GitHub Actions logs."}' \
              "${{ secrets.SLACK_WEBHOOK_URL }}"
          fi

      - name: Summary
        if: always()
        run: echo "Pipeline completed at $(date -u). Exit code: $?"
